### Currently Learning "version control with git" on Hamoye Internship platform

In [1]:
# project one
import numpy as np

In [2]:
import pandas as pd

In [3]:
np.random.randint(1, 10, (4, 4))

array([[3, 2, 8, 6],
       [4, 7, 7, 7],
       [2, 6, 1, 1],
       [6, 8, 5, 7]])

#### I'm trying to test my connection between google colab and github

In [4]:
np.random.rand(2, 7)

array([[0.27812292, 0.73445572, 0.48999628, 0.94211334, 0.16930523,
        0.33012791, 0.21963735],
       [0.79353666, 0.14513263, 0.17554579, 0.07467329, 0.37260378,
        0.03891397, 0.03425094]])

Tested it out!

It worked just fine. Hurray!!!

In [6]:
np.random.rand(1, 10)

array([[0.78975448, 0.94351833, 0.61426221, 0.8963893 , 0.28723661,
        0.1001172 , 0.89867994, 0.09751886, 0.64173028, 0.6268173 ]])